In [1132]:
import numpy as np
import random 
import gym
import matplotlib.pyplot as plt

## Frozen lake

In [453]:
env = gym.make("FrozenLake-v0")

action_size = env.action_space.n
state_size = env.observation_space.n

qtable = np.zeros((state_size, action_size))
print(qtable)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [1173]:
# epsilon-greedy policy 
def eps_greedy(epsilon,qtable,state):
    rn = random.uniform(0,1)
    
    # maximize
    if(rn > epsilon):
        action = np.argmax(qtable[state,:])
    else:
        #print('random action')
        action = random.sample(range(action_size),1)[0]
    
    return action


# updates the q values 
def update_qvalue(state,action,new_state,learning_rate,rew,gamma,qtable):
    
    curr_val = qtable[state,action]
    
    qtable[state,action] = curr_val + learning_rate*(rew + (gamma*np.max(qtable[new_state,:])) - curr_val)
    
    

    

In [455]:

#update_qvalue(0,2,3,learning_rate,2,gamma,qtable)

In [1142]:
total_episodes = 10000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob


In [457]:
def q_learning(total_episodes,max_steps,qtable,epsilon,learning_rate,gamma,decay_rate):
    # Q learning 

    reward = [] #list of rewards at the end of each episode
    all_steps = []

    for i in range(1,total_episodes):
        #at beginning of every episode reset the environment
        state = env.reset()
        total_rewards = 0
        total_steps = 0
        for step in range(max_steps):

            action = eps_greedy(epsilon,qtable,state) #choose action according to epsilon-greedy

            # now take a step in the environment 
            new_state,rew,done,inf = env.step(action)  #env.step returns next state, reward , done flag (if T indicates time to reset the env),
                                                   #and info which is dict for useful debugging. 

            #update the qtable
            update_qvalue(state,action,new_state,learning_rate,rew,gamma,qtable)


            total_rewards = total_rewards + rew

            state = new_state

            if(done=='True'):
                break

        epsilon = 1*np.exp(-decay_rate*i)
        reward.append(total_rewards)
        all_steps.append(step)
    
    return reward,all_steps,qtable

r,s,q = q_learning(total_episodes,max_steps,qtable,epsilon,learning_rate,gamma,decay_rate)

    

In [460]:
print(q)

[[  3.43732158e-01   1.18715774e-02   1.15848174e-02   1.21763614e-02]
 [  2.23409044e-03   4.63406508e-03   5.56537808e-03   1.53738467e-01]
 [  3.00721612e-03   3.68636658e-03   2.77133294e-03   1.16143835e-01]
 [  2.73277601e-03   2.03175203e-03   1.67626695e-03   9.52136282e-02]
 [  5.53618613e-01   1.53078780e-02   8.90277599e-03   6.04939524e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.12968416e-01   1.47413982e-06   1.23333666e-06   4.27445807e-07]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.34545229e-03   3.02822889e-03   3.40195312e-03   2.58222328e-01]
 [  7.59776547e-03   4.19721481e-02   6.28730954e-03   5.42094823e-03]
 [  7.59024209e-01   4.75392412e-04   7.67766788e-04   3.96250864e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.41004091e-02   4.76954324e-02   8.88948199e-01   2.76761913e-02]
 [  9.

In [478]:
# play the game

env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            break
        state = new_state
env.close()



****************************************************
EPISODE  0

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
****************************************************
EPISODE  1

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFF

## Cliff walking

In [1172]:
### make environment
class cliffwalker:
    
    # 0 UP 1 LEFT 2 DOWN 3 RIGHT

    #init variables
    def __init__(self, nA, nS):
        self.pos = (3,0)
        self.A = nA
        self.S = nS
        self.mat = np.zeros([nA,nS//nA],dtype=str)                
        for i in range(self.mat.shape[0]-1):
            for j in range(self.mat.shape[1]):
                self.mat[i][j] = 'O'
        
        self.mat[3][0] = 'S'
        self.mat[3][11] = 'T'
        self.mat[3][1:11] = 'C'
        print(self.mat)
    
    #reset environment , player starts at 3,0 after reset
    def reset_env(self):
        self.pos = (3,0)
        
        return self.pos_to_state(self.pos)
    
    #define all action movements
    def action_space(self,action):
        
        #self.pos = self.state_to_pos(self.pos)
        old_pos = self.pos
        
        
        if action == 0: #UP
            if self.pos[0]==0: #and (0 <= new_pos[1] <12): #if at boundary 
                new_pos = self.pos
            else:
                new_pos = (self.pos[0] - 1 , self.pos[1] )
            
        if action == 1: #LEFT
            if self.pos[1]==0: #and (0 <= new_pos[0] <4): #if at boundary 
                new_pos = self.pos
            else:
                new_pos = (self.pos[0],self.pos[1] - 1)
                
        if action == 2: #Down
            if self.pos[0] == 3:
                new_pos = self.pos
            else:
                new_pos = (self.pos[0] + 1 , self.pos[1])
        if action == 3: #RIGHT
            if self.pos[1] == 11:
                new_pos = self.pos
            else:
                new_pos = (self.pos[0] , self.pos[1] + 1)
        

        self.pos = new_pos
        
        
        return(self.pos,old_pos)
    
    # based on the new action define the reward
    def reward(self,action):
        #done = False
        p,o = self.action_space(action) #p is the new position, o is the old position
        
        if p==o:
            rew = -1
            done = False
            
        elif p[0]==3 and ( 0 < p[1] < 11 ) : 
            rew = -100
            self.pos = self.reset_env()
            self.pos = self.state_to_pos(self.pos)
            done = True
        
        elif (p[0] == 3) and (p[1] == 11):
            rew = 1 
            self.pos = self.reset_env()
            self.pos = self.state_to_pos(self.pos)
            done = True
            
            #if none of this
        else:
            rew = -1
            done = False
            
        return p,rew,done
    # executes the action i.e. runs one simulation of the enviroment
    def render(self,action):
        
        p,rew,done = self.reward(action)
        self.mat[p[0]][p[1]] = 'X'
        #print(p,rew,done)
        #print(self.mat)
        self.mat[p[0]][p[1]] = 'O'
        return self.pos_to_state(p),rew,done
    

        
    # map position to state id
    def pos_to_state(self,posn):
        return posn[0]*12 + posn[1]
    
    #map state id to position
    def state_to_pos(self,stateid):
        return (stateid // 12 , stateid % 12)
        
        
        
    

In [1174]:
#hyper parameters 

total_episodes = 10000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob


In [1175]:
instance = cliffwalker(4,48) #cliff walker object
instance.reset_env() # reset the environment 

action_size = instance.A 
state_size = instance.S 

qtable = np.zeros((state_size, action_size))
#print(qtable)


[['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['S' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'T']]


In [1177]:
#### q learning algorithm for Cliff walker  

def q_learning(total_episodes,max_steps,qtable,epsilon,learning_rate,gamma,decay_rate):
    # Q learning 

    reward = [] #list of rewards at the end of each episode
    all_steps = []

    for i in range(1,total_episodes):
        #at beginning of every episode reset the environment
        state = instance.reset_env()
        total_rewards = 0
        total_steps = 0
        for step in range(max_steps):

            action = eps_greedy(epsilon,qtable,state) #choose action according to epsilon-greedy

            # now take a step in the environment 
            new_state,rew,done = instance.render(action)  #env.step returns next state, reward , done flag (if T indicates time to reset the env),
                                                   #and info which is dict for useful debugging. 

            #update the qtable
            update_qvalue(state,action,new_state,learning_rate,rew,gamma,qtable)


            total_rewards = total_rewards + rew

            state = new_state

            if(done=='True'):
                break

        epsilon = 1*np.exp(-decay_rate*i)
        reward.append(total_rewards)
        all_steps.append(step)
    
    return reward,all_steps,qtable

r,s,q = q_learning(total_episodes,max_steps,qtable,epsilon,learning_rate,gamma,decay_rate)

    

In [1179]:
# function to show player position
def print_grid(new_state,nA = 4, nS = 48):
    
    mat = np.zeros([nA,nS//nA],dtype=str)                
    for i in range(mat.shape[0]-1):
        for j in range(mat.shape[1]):
            mat[i][j] = 'O'
        
    mat[3][0] = 'S'
    mat[3][11] = 'T'
    mat[3][1:11] = 'C'
    
    p = (new_state // 12 , new_state % 12)
    mat[p[0]][p[1]] = 'X'
    print(mat)
    mat[p[0]][p[1]] = 'O'
    

In [1180]:
# play the game


    

instance.reset_env()

for episode in range(5):
    state = instance.reset_env()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done = instance.render(action)
        print(new_state)
        print_grid(new_state)
        
        if done:
            break
        state = new_state
print('Done')



****************************************************
EPISODE  0
24
[['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['X' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['S' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'T']]
25
[['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'X' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['S' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'T']]
26
[['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'X' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['S' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'T']]
27
[['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'X' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['S' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'T']]
28
[['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']